Repository arcalos-management/environment-arcalos-staging-mgmt-dev, pull requests merged in 2020-04, with the labels that each got.

#1 feat: make environment ready for use
  env/bucketrepo/values.tmpl.yaml
  env/jx-app-datadog/values.tmpl.yaml
  env/jx-app-kuberhealthy/README.MD
  env/jx-app-kuberhealthy/templates/app.yaml
  env/jx-app-kuberhealthy/values.yaml
  env/jx-tenant-service/values.tmpl.yaml
  env/jxboot-resources/values.tmpl.yaml
  env/lighthouse-githubapp/values.tmpl.yaml
  env/nexus/values.tmpl.yaml
  env/parameters.tmpl.schema.json
  env/parameters.yaml
  env/requirements.yaml
  env/templates/700-lighthouse-githubapp-ingress.yaml
  env/templates/arcalos-alpha-prod-secret.yaml
  env/templates/arcalos-config-configmap.yaml
  env/templates/arcalos-scheduler.yaml
  env/templates/datadog-dogrc-secret.yaml
  env/values.tmpl.yaml
  jx-requirements.yml
Labels: approved, lgtm, size/L

#2 fix: disabled updateController
  env/jx-tenant-service/values.tmpl.yaml
Labels: approved, size/XS

#3 chore: rox jx-tenant-service apiKey
  env/jx-tenant-service/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#4 chore: jx-tenant-service to 0.0.660
  env/requirements.yaml
Labels: approved, lgtm, size/XS

#6 chore: jx-tenant-service to 0.0.662
  env/requirements.yaml
Labels: approved, lgtm, size/XS

#5 feat: add jx-tenant-service ingress templates
  env/templates/700-jx-tenant-service-ing.yaml
  env/templates/701-boot-tenant-service-ing.yaml
  env/values.tmpl.yaml
Labels: approved, lgtm, size/M

#7 feat: Add jxui-arcalos
  env/jxui-arcalos/values.tmpl.yaml
  env/requirements.yaml
Labels: approved, lgtm, size/S

#10 Add oauth-proxy-jxui-backend
  env/oauth-proxy-jxui-backend/values.tmpl.yaml
  env/parameters.tmpl.schema.json
  env/parameters.yaml
  env/requirements.yaml
Labels: approved, lgtm, size/M

#12 Add oauth-proxy-jxui-frontend
  env/oauth-proxy-jxui-frontend/values.tmpl.yaml
  env/requirements.yaml
Labels: approved, lgtm, size/S

#13 chore: remove non required kube providers
  kubeProviders/aks/README.md
  kubeProviders/aks/values.tmpl.yaml
  kubeProviders/alibaba/README.md
  kubeProviders/alibaba/values.tmpl.yaml
  kubeProviders/aws/README.md
  kubeProviders/aws/values.tmpl.yaml
  kubeProviders/eks/README.md
  kubeProviders/eks/templates/irsa.tmpl.yaml
  kubeProviders/eks/templates/jenkinsx-policies.yml
  kubeProviders/eks/templates/vault_cf_tmpl.yml
  kubeProviders/eks/values.tmpl.yaml
  kubeProviders/icp/README.md
  kubeProviders/icp/values.tmpl.yaml
  kubeProviders/iks/README.md
  kubeProviders/iks/values.tmpl.yaml
  kubeProviders/minikube/values.tmpl.yaml
  kubeProviders/minishift/values.tmpl.yaml
  kubeProviders/oke/README.md
  kubeProviders/oke/values.tmpl.yaml
  kubeProviders/openshift/values.tmpl.yaml
  kubeProviders/pks/README.md
  kubeProviders/pks/values.tmpl.yaml
Labels: approved, lgtm, size/XL

#21 fix: attempt to resolve SSO dependency for jxui
  env/jxui-arcalos/templates/sso-crd.yaml
Labels: approved, lgtm, size/S

#22 fix: resolve template file
  env/jxui-arcalos/templates/sso-crd.tmpl.yaml
Labels: approved, lgtm, size/XS

#26 chore: remove jxui-arcalos sso template
  env/jxui-arcalos/templates/sso-crd.tmpl.yaml
Labels: approved, lgtm, size/S

#27 chore: re-enable updateController
  env/jx-tenant-service/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#28 fix: attempt to disable the use of SSO Operator
  env/jxui-arcalos/values.tmpl.yaml
  env/requirements.yaml
Labels: approved, lgtm, size/XS

#25 feat: add dashboard domain
  env/templates/700-jxui-backend-ing.yaml
  env/templates/700-jxui-ing.yaml
  systems/acme/Makefile
  systems/acme/templates/cert-manager-prod-certificate.yaml
  systems/acme/templates/cert-manager-prod-issuer.yaml
  systems/acme/templates/cert-manager-staging-certificate.yaml
  systems/acme/templates/cert-manager-staging-issuer.yaml
  systems/acme/values.tmpl.yaml
Labels: approved, lgtm, size/L

#29 fix: add basicAuth secret for arcalos pipeline
  env/templates/basic-auth-secret.yaml
Labels: approved, lgtm, size/XS

#33 fix: add bot name for environment
  env/lighthouse-githubapp/values.tmpl.yaml
Labels: approved, lgtm, size/XS
